# CMake generated Testfile for 
# Source directory: /home/rajendra/ws_moveit/src/moveit/moveit_core/collision_detection
# Build directory: /home/rajendra/ws_moveit/build_isolated/moveit_core/collision_detection
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_core_gtest_test_world "/home/rajendra/ws_moveit/build_isolated/moveit_core/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_core/test_results/moveit_core/gtest-test_world.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/moveit_core/lib/moveit_core/test_world --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/moveit_core/test_results/moveit_core/gtest-test_world.xml")
add_test(_ctest_moveit_core_gtest_test_world_diff "/home/rajendra/ws_moveit/build_isolated/moveit_core/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_core/test_results/moveit_core/gtest-test_world_diff.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/moveit_core/lib/moveit_core/test_world_diff --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/moveit_core/test_results/moveit_core/gtest-test_world_diff.xml")
add_test(_ctest_moveit_core_gtest_test_all_valid "/home/rajendra/ws_moveit/build_isolated/moveit_core/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_core/test_results/moveit_core/gtest-test_all_valid.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/moveit_core/lib/moveit_core/test_all_valid --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/moveit_core/test_results/moveit_core/gtest-test_all_valid.xml")
