# CMake generated Testfile for 
# Source directory: /home/rajendra/ws_moveit/src/moveit/moveit_kinematics/test
# Build directory: /home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_kinematics_rostest_fanuc-kdl__ik_plugin_kdl_kinematics_plugin_KDLKinematicsPlugin.test "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results/moveit_kinematics/rostest-fanuc-kdl__ik_plugin_kdl_kinematics_plugin_KDLKinematicsPlugin.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_kinematics --package=moveit_kinematics --results-filename fanuc-kdl__ik_plugin_kdl_kinematics_plugin_KDLKinematicsPlugin.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_kinematics/test/fanuc-kdl.test ik_plugin:=kdl_kinematics_plugin/KDLKinematicsPlugin")
add_test(_ctest_moveit_kinematics_rostest_panda-kdl__ik_plugin_kdl_kinematics_plugin_KDLKinematicsPlugin.test "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results/moveit_kinematics/rostest-panda-kdl__ik_plugin_kdl_kinematics_plugin_KDLKinematicsPlugin.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_kinematics --package=moveit_kinematics --results-filename panda-kdl__ik_plugin_kdl_kinematics_plugin_KDLKinematicsPlugin.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_kinematics/test/panda-kdl.test ik_plugin:=kdl_kinematics_plugin/KDLKinematicsPlugin")
add_test(_ctest_moveit_kinematics_rostest_fanuc-kdl__ik_plugin_lma_kinematics_plugin_LMAKinematicsPlugin__tolerance_0.0005.test "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results/moveit_kinematics/rostest-fanuc-kdl__ik_plugin_lma_kinematics_plugin_LMAKinematicsPlugin__tolerance_0.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_kinematics --package=moveit_kinematics --results-filename fanuc-kdl__ik_plugin_lma_kinematics_plugin_LMAKinematicsPlugin__tolerance_0.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_kinematics/test/fanuc-kdl.test ik_plugin:=lma_kinematics_plugin/LMAKinematicsPlugin tolerance:=0.0005")
add_test(_ctest_moveit_kinematics_rostest_panda-kdl__ik_plugin_lma_kinematics_plugin_LMAKinematicsPlugin__tolerance_0.0005.test "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results/moveit_kinematics/rostest-panda-kdl__ik_plugin_lma_kinematics_plugin_LMAKinematicsPlugin__tolerance_0.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_kinematics --package=moveit_kinematics --results-filename panda-kdl__ik_plugin_lma_kinematics_plugin_LMAKinematicsPlugin__tolerance_0.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_kinematics/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_kinematics/test/panda-kdl.test ik_plugin:=lma_kinematics_plugin/LMAKinematicsPlugin tolerance:=0.0005")
