set(_CATKIN_CURRENT_PACKAGE "moveit_core")
set(moveit_core_VERSION "1.0.1")
set(moveit_core_MAINTAINER "Dave Coleman <dave@picknik.ai>, Michael Görner <me@v4hn.de>, Michael Ferguson <mferguson@fetchrobotics.com>, MoveIt Release Team <moveit_releasers@googlegroups.com>")
set(moveit_core_PACKAGE_FORMAT "2")
set(moveit_core_BUILD_DEPENDS "assimp" "boost" "eigen" "eigen_stl_containers" "libfcl-dev" "geometric_shapes" "geometry_msgs" "kdl_parser" "libconsole-bridge-dev" "urdf" "liburdfdom-dev" "liburdfdom-headers-dev" "moveit_msgs" "octomap" "octomap_msgs" "random_numbers" "roslib" "rostime" "rosconsole" "sensor_msgs" "shape_msgs" "srdfdom" "std_msgs" "tf2_eigen" "tf2_geometry_msgs" "trajectory_msgs" "visualization_msgs" "xmlrpcpp")
set(moveit_core_BUILD_DEPENDS_geometric_shapes_VERSION_GTE "0.5.2")
set(moveit_core_BUILD_EXPORT_DEPENDS "assimp" "boost" "eigen" "eigen_stl_containers" "libfcl-dev" "geometric_shapes" "geometry_msgs" "kdl_parser" "libconsole-bridge-dev" "urdf" "liburdfdom-dev" "liburdfdom-headers-dev" "moveit_msgs" "octomap" "octomap_msgs" "random_numbers" "roslib" "rostime" "rosconsole" "sensor_msgs" "shape_msgs" "srdfdom" "std_msgs" "tf2_eigen" "tf2_geometry_msgs" "trajectory_msgs" "visualization_msgs" "xmlrpcpp")
set(moveit_core_BUILD_EXPORT_DEPENDS_geometric_shapes_VERSION_GTE "0.5.2")
set(moveit_core_BUILDTOOL_DEPENDS "catkin" "pkg-config")
set(moveit_core_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_core_EXEC_DEPENDS "assimp" "boost" "eigen" "eigen_stl_containers" "libfcl-dev" "geometric_shapes" "geometry_msgs" "kdl_parser" "libconsole-bridge-dev" "urdf" "liburdfdom-dev" "liburdfdom-headers-dev" "moveit_msgs" "octomap" "octomap_msgs" "random_numbers" "roslib" "rostime" "rosconsole" "sensor_msgs" "shape_msgs" "srdfdom" "std_msgs" "tf2_eigen" "tf2_geometry_msgs" "trajectory_msgs" "visualization_msgs" "xmlrpcpp")
set(moveit_core_EXEC_DEPENDS_geometric_shapes_VERSION_GTE "0.5.2")
set(moveit_core_RUN_DEPENDS "assimp" "boost" "eigen" "eigen_stl_containers" "libfcl-dev" "geometric_shapes" "geometry_msgs" "kdl_parser" "libconsole-bridge-dev" "urdf" "liburdfdom-dev" "liburdfdom-headers-dev" "moveit_msgs" "octomap" "octomap_msgs" "random_numbers" "roslib" "rostime" "rosconsole" "sensor_msgs" "shape_msgs" "srdfdom" "std_msgs" "tf2_eigen" "tf2_geometry_msgs" "trajectory_msgs" "visualization_msgs" "xmlrpcpp")
set(moveit_core_RUN_DEPENDS_geometric_shapes_VERSION_GTE "0.5.2")
set(moveit_core_TEST_DEPENDS "moveit_resources" "angles" "tf2_kdl" "orocos_kdl" "rosunit")
set(moveit_core_DOC_DEPENDS )
set(moveit_core_URL_WEBSITE "http://moveit.ros.org")
set(moveit_core_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(moveit_core_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(moveit_core_DEPRECATED "")