// Auto-generated. Do not edit!

// (in-package moveit_task_constructor_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ExecuteTaskSolutionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.sub_id = null;
      this.sub_no = null;
    }
    else {
      if (initObj.hasOwnProperty('sub_id')) {
        this.sub_id = initObj.sub_id
      }
      else {
        this.sub_id = 0;
      }
      if (initObj.hasOwnProperty('sub_no')) {
        this.sub_no = initObj.sub_no
      }
      else {
        this.sub_no = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExecuteTaskSolutionFeedback
    // Serialize message field [sub_id]
    bufferOffset = _serializer.uint32(obj.sub_id, buffer, bufferOffset);
    // Serialize message field [sub_no]
    bufferOffset = _serializer.uint32(obj.sub_no, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExecuteTaskSolutionFeedback
    let len;
    let data = new ExecuteTaskSolutionFeedback(null);
    // Deserialize message field [sub_id]
    data.sub_id = _deserializer.uint32(buffer, bufferOffset);
    // Deserialize message field [sub_no]
    data.sub_no = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'moveit_task_constructor_msgs/ExecuteTaskSolutionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5b60fd9ace7afa0cb3eb2c409d0732ed';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # finished subtrajectory id / number
    uint32 sub_id
    uint32 sub_no
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExecuteTaskSolutionFeedback(null);
    if (msg.sub_id !== undefined) {
      resolved.sub_id = msg.sub_id;
    }
    else {
      resolved.sub_id = 0
    }

    if (msg.sub_no !== undefined) {
      resolved.sub_no = msg.sub_no;
    }
    else {
      resolved.sub_no = 0
    }

    return resolved;
    }
};

module.exports = ExecuteTaskSolutionFeedback;
