(cl:in-package moveit_msgs-msg)
(cl:export '(WORKSPACE_PARAMETERS-VAL
          WORKSPACE_PARAMETERS
          START_STATE-VAL
          START_STATE
          GOAL_CONSTRAINTS-VAL
          GOAL_CONSTRAINTS
          PATH_CONSTRAINTS-VAL
          PATH_CONSTRAINTS
          TRAJECTORY_CONSTRAINTS-VAL
          TRAJECTORY_CONSTRAINTS
          REFERENCE_TRAJECTORIES-VAL
          REFERENCE_TRAJECTORIES
          PLANNER_ID-VAL
          PLANNER_ID
          GROUP_NAME-VAL
          GROUP_NAME
          NUM_PLANNING_ATTEMPTS-VAL
          NUM_PLANNING_ATTEMPTS
          ALLOWED_PLANNING_TIME-VAL
          ALLOWED_PLANNING_TIME
          MAX_VELOCITY_SCALING_FACTOR-VAL
          MAX_VELOCITY_SCALING_FACTOR
          MAX_ACCELERATION_SCALING_FACTOR-VAL
          MAX_ACCELERATION_SCALING_FACTOR
))