set(_CATKIN_CURRENT_PACKAGE "moveit_task_constructor_capabilities")
set(moveit_task_constructor_capabilities_VERSION "0.0.0")
set(moveit_task_constructor_capabilities_MAINTAINER "Michael v4hn Goerner <me@v4hn.de>, Robert Haschke <rhaschke@techfak.uni-bielefeld.de>")
set(moveit_task_constructor_capabilities_PACKAGE_FORMAT "2")
set(moveit_task_constructor_capabilities_BUILD_DEPENDS "moveit_core" "moveit_ros_move_group" "actionlib" "pluginlib" "std_msgs" "moveit_task_constructor_msgs")
set(moveit_task_constructor_capabilities_BUILD_EXPORT_DEPENDS "moveit_core" "moveit_ros_move_group" "actionlib" "pluginlib" "std_msgs" "moveit_task_constructor_msgs")
set(moveit_task_constructor_capabilities_BUILDTOOL_DEPENDS "catkin")
set(moveit_task_constructor_capabilities_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_task_constructor_capabilities_EXEC_DEPENDS "moveit_core" "moveit_ros_move_group" "actionlib" "pluginlib" "std_msgs" "moveit_task_constructor_msgs")
set(moveit_task_constructor_capabilities_RUN_DEPENDS "moveit_core" "moveit_ros_move_group" "actionlib" "pluginlib" "std_msgs" "moveit_task_constructor_msgs")
set(moveit_task_constructor_capabilities_TEST_DEPENDS )
set(moveit_task_constructor_capabilities_DOC_DEPENDS )
set(moveit_task_constructor_capabilities_URL_WEBSITE "")
set(moveit_task_constructor_capabilities_URL_BUGTRACKER "")
set(moveit_task_constructor_capabilities_URL_REPOSITORY "")
set(moveit_task_constructor_capabilities_DEPRECATED "")