set(_CATKIN_CURRENT_PACKAGE "moveit_pr2")
set(moveit_pr2_VERSION "0.7.3")
set(moveit_pr2_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>")
set(moveit_pr2_PACKAGE_FORMAT "2")
set(moveit_pr2_BUILD_DEPENDS )
set(moveit_pr2_BUILD_EXPORT_DEPENDS )
set(moveit_pr2_BUILDTOOL_DEPENDS "catkin")
set(moveit_pr2_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_pr2_EXEC_DEPENDS "pr2_moveit_config" "pr2_moveit_plugins")
set(moveit_pr2_RUN_DEPENDS "pr2_moveit_config" "pr2_moveit_plugins")
set(moveit_pr2_TEST_DEPENDS )
set(moveit_pr2_DOC_DEPENDS )
set(moveit_pr2_URL_WEBSITE "http://moveit.ros.org")
set(moveit_pr2_URL_BUGTRACKER "")
set(moveit_pr2_URL_REPOSITORY "")
set(moveit_pr2_DEPRECATED "")