# CMake generated Testfile for 
# Source directory: /home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface/test
# Build directory: /home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_moveit_ros_planning_interface_rostest_test_moveit_cpp_test.test "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rostest-test_moveit_cpp_test.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface --package=moveit_ros_planning_interface --results-filename test_moveit_cpp_test.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface/test/moveit_cpp_test.test ")
add_test(_ctest_moveit_ros_planning_interface_rostest_test_python_move_group.test "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rostest-test_python_move_group.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface --package=moveit_ros_planning_interface --results-filename test_python_move_group.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface/test/python_move_group.test ")
add_test(_ctest_moveit_ros_planning_interface_rostest_test_python_move_group_ns.test "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rostest-test_python_move_group_ns.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface --package=moveit_ros_planning_interface --results-filename test_python_move_group_ns.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface/test/python_move_group_ns.test ")
add_test(_ctest_moveit_ros_planning_interface_rostest_test_robot_state_update.test "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rostest-test_robot_state_update.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface --package=moveit_ros_planning_interface --results-filename test_robot_state_update.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface/test/robot_state_update.test ")
add_test(_ctest_moveit_ros_planning_interface_rostest_test_cleanup.test "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rostest-test_cleanup.xml" "--return-code" "/opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface --package=moveit_ros_planning_interface --results-filename test_cleanup.xml --results-base-dir \"/home/rajendra/ws_moveit/build_isolated/moveit_ros_planning_interface/test_results\" /home/rajendra/ws_moveit/src/moveit/moveit_ros/planning_interface/test/cleanup.test ")
