set(moveit_ros_visualization_SETUP_PY_VERSION "1.0.1")
set(moveit_ros_visualization_SETUP_PY_SCRIPTS "")
set(moveit_ros_visualization_SETUP_PY_PACKAGES "moveit_ros_visualization")
set(moveit_ros_visualization_SETUP_PY_PACKAGE_DIRS "src/moveit_ros_visualization")
set(moveit_ros_visualization_SETUP_PY_MODULES "")
set(moveit_ros_visualization_SETUP_PY_MODULE_DIRS "")