# CMake generated Testfile for 
# Source directory: /home/rajendra/ws_moveit/src/geometric_shapes/test
# Build directory: /home/rajendra/ws_moveit/build_isolated/geometric_shapes/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_geometric_shapes_gtest_test_point_inclusion "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_point_inclusion.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/geometric_shapes/lib/geometric_shapes/test_point_inclusion --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_point_inclusion.xml")
add_test(_ctest_geometric_shapes_gtest_test_bounding_sphere "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_bounding_sphere.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/geometric_shapes/lib/geometric_shapes/test_bounding_sphere --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_bounding_sphere.xml")
add_test(_ctest_geometric_shapes_gtest_test_bounding_box "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_bounding_box.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/geometric_shapes/lib/geometric_shapes/test_bounding_box --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_bounding_box.xml")
add_test(_ctest_geometric_shapes_gtest_test_create_mesh "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_create_mesh.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/geometric_shapes/lib/geometric_shapes/test_create_mesh --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_create_mesh.xml")
add_test(_ctest_geometric_shapes_gtest_test_loaded_meshes "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_loaded_meshes.xml" "--return-code" "/home/rajendra/ws_moveit/devel_isolated/geometric_shapes/lib/geometric_shapes/test_loaded_meshes --gtest_output=xml:/home/rajendra/ws_moveit/build_isolated/geometric_shapes/test_results/geometric_shapes/gtest-test_loaded_meshes.xml")
