set(_CATKIN_CURRENT_PACKAGE "moveit_task_constructor_msgs")
set(moveit_task_constructor_msgs_VERSION "0.0.0")
set(moveit_task_constructor_msgs_MAINTAINER "Robert Haschke <rhaschke@techfak.uni-bielefeld.de>, Michael Goerner <me@v4hn.de>")
set(moveit_task_constructor_msgs_PACKAGE_FORMAT "2")
set(moveit_task_constructor_msgs_BUILD_DEPENDS "message_generation" "moveit_msgs" "visualization_msgs")
set(moveit_task_constructor_msgs_BUILD_EXPORT_DEPENDS "message_generation" "moveit_msgs" "visualization_msgs")
set(moveit_task_constructor_msgs_BUILDTOOL_DEPENDS "catkin")
set(moveit_task_constructor_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_task_constructor_msgs_EXEC_DEPENDS "message_runtime" "message_generation" "moveit_msgs" "visualization_msgs")
set(moveit_task_constructor_msgs_RUN_DEPENDS "message_runtime" "message_generation" "moveit_msgs" "visualization_msgs")
set(moveit_task_constructor_msgs_TEST_DEPENDS )
set(moveit_task_constructor_msgs_DOC_DEPENDS )
set(moveit_task_constructor_msgs_URL_WEBSITE "")
set(moveit_task_constructor_msgs_URL_BUGTRACKER "")
set(moveit_task_constructor_msgs_URL_REPOSITORY "")
set(moveit_task_constructor_msgs_DEPRECATED "")