// Generated by gencpp from file moveit_task_constructor_msgs/GetSolution.msg
// DO NOT EDIT!


#ifndef MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_GETSOLUTION_H
#define MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_GETSOLUTION_H

#include <ros/service_traits.h>


#include <moveit_task_constructor_msgs/GetSolutionRequest.h>
#include <moveit_task_constructor_msgs/GetSolutionResponse.h>


namespace moveit_task_constructor_msgs
{

struct GetSolution
{

typedef GetSolutionRequest Request;
typedef GetSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSolution
} // namespace moveit_task_constructor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_task_constructor_msgs::GetSolution > {
  static const char* value()
  {
    return "7b2d5747af4b538b9e0ff8d9e2919f3b";
  }

  static const char* value(const ::moveit_task_constructor_msgs::GetSolution&) { return value(); }
};

template<>
struct DataType< ::moveit_task_constructor_msgs::GetSolution > {
  static const char* value()
  {
    return "moveit_task_constructor_msgs/GetSolution";
  }

  static const char* value(const ::moveit_task_constructor_msgs::GetSolution&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_task_constructor_msgs::GetSolutionRequest> should match 
// service_traits::MD5Sum< ::moveit_task_constructor_msgs::GetSolution > 
template<>
struct MD5Sum< ::moveit_task_constructor_msgs::GetSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_task_constructor_msgs::GetSolution >::value();
  }
  static const char* value(const ::moveit_task_constructor_msgs::GetSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_task_constructor_msgs::GetSolutionRequest> should match 
// service_traits::DataType< ::moveit_task_constructor_msgs::GetSolution > 
template<>
struct DataType< ::moveit_task_constructor_msgs::GetSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_task_constructor_msgs::GetSolution >::value();
  }
  static const char* value(const ::moveit_task_constructor_msgs::GetSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_task_constructor_msgs::GetSolutionResponse> should match 
// service_traits::MD5Sum< ::moveit_task_constructor_msgs::GetSolution > 
template<>
struct MD5Sum< ::moveit_task_constructor_msgs::GetSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_task_constructor_msgs::GetSolution >::value();
  }
  static const char* value(const ::moveit_task_constructor_msgs::GetSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_task_constructor_msgs::GetSolutionResponse> should match 
// service_traits::DataType< ::moveit_task_constructor_msgs::GetSolution > 
template<>
struct DataType< ::moveit_task_constructor_msgs::GetSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_task_constructor_msgs::GetSolution >::value();
  }
  static const char* value(const ::moveit_task_constructor_msgs::GetSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_GETSOLUTION_H
