// Generated by gencpp from file moveit_task_constructor_msgs/StageStatistics.msg
// DO NOT EDIT!


#ifndef MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_STAGESTATISTICS_H
#define MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_STAGESTATISTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_task_constructor_msgs
{
template <class ContainerAllocator>
struct StageStatistics_
{
  typedef StageStatistics_<ContainerAllocator> Type;

  StageStatistics_()
    : id(0)
    , solved()
    , failed()
    , num_failed(0)  {
    }
  StageStatistics_(const ContainerAllocator& _alloc)
    : id(0)
    , solved(_alloc)
    , failed(_alloc)
    , num_failed(0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _solved_type;
  _solved_type solved;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _failed_type;
  _failed_type failed;

   typedef uint32_t _num_failed_type;
  _num_failed_type num_failed;





  typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> const> ConstPtr;

}; // struct StageStatistics_

typedef ::moveit_task_constructor_msgs::StageStatistics_<std::allocator<void> > StageStatistics;

typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageStatistics > StageStatisticsPtr;
typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageStatistics const> StageStatisticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveit_task_constructor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/melodic/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/home/rajendra/ws_moveit/devel/share/moveit_msgs/msg', '/home/rajendra/ws_moveit/src/moveit_msgs/msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/melodic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/melodic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg'], 'moveit_task_constructor_msgs': ['/home/rajendra/ws_moveit/src/moveit_task_constructor/msgs/msg', '/home/rajendra/ws_moveit/devel/share/moveit_task_constructor_msgs/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce0a061efd72c8d723e25e561f7c2179";
  }

  static const char* value(const ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce0a061efd72c8d7ULL;
  static const uint64_t static_value2 = 0x23e25e561f7c2179ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_task_constructor_msgs/StageStatistics";
  }

  static const char* value(const ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# dynamically changing information for a stage\n"
"\n"
"# unique id within task\n"
"uint32 id\n"
"\n"
"# successful solution IDs of this stage\n"
"uint32[] solved\n"
"\n"
"# (optional) failed solution IDs of this stage\n"
"uint32[] failed\n"
"# number of failed solutions (if failed is empty)\n"
"uint32   num_failed\n"
;
  }

  static const char* value(const ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.solved);
      stream.next(m.failed);
      stream.next(m.num_failed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StageStatistics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_task_constructor_msgs::StageStatistics_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "solved[]" << std::endl;
    for (size_t i = 0; i < v.solved.size(); ++i)
    {
      s << indent << "  solved[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.solved[i]);
    }
    s << indent << "failed[]" << std::endl;
    for (size_t i = 0; i < v.failed.size(); ++i)
    {
      s << indent << "  failed[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.failed[i]);
    }
    s << indent << "num_failed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_failed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_STAGESTATISTICS_H
