// Generated by gencpp from file moveit_task_constructor_msgs/StageDescription.msg
// DO NOT EDIT!


#ifndef MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_STAGEDESCRIPTION_H
#define MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_STAGEDESCRIPTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <moveit_task_constructor_msgs/Property.h>

namespace moveit_task_constructor_msgs
{
template <class ContainerAllocator>
struct StageDescription_
{
  typedef StageDescription_<ContainerAllocator> Type;

  StageDescription_()
    : id(0)
    , parent_id(0)
    , name()
    , flags(0)
    , properties()  {
    }
  StageDescription_(const ContainerAllocator& _alloc)
    : id(0)
    , parent_id(0)
    , name(_alloc)
    , flags(0)
    , properties(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef uint32_t _parent_id_type;
  _parent_id_type parent_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint32_t _flags_type;
  _flags_type flags;

   typedef std::vector< ::moveit_task_constructor_msgs::Property_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::moveit_task_constructor_msgs::Property_<ContainerAllocator> >::other >  _properties_type;
  _properties_type properties;





  typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> const> ConstPtr;

}; // struct StageDescription_

typedef ::moveit_task_constructor_msgs::StageDescription_<std::allocator<void> > StageDescription;

typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageDescription > StageDescriptionPtr;
typedef boost::shared_ptr< ::moveit_task_constructor_msgs::StageDescription const> StageDescriptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveit_task_constructor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/melodic/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/home/rajendra/ws_moveit/devel/share/moveit_msgs/msg', '/home/rajendra/ws_moveit/src/moveit_msgs/msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/melodic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/melodic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg'], 'moveit_task_constructor_msgs': ['/home/rajendra/ws_moveit/src/moveit_task_constructor/msgs/msg', '/home/rajendra/ws_moveit/devel/share/moveit_task_constructor_msgs/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eae8b915a082df4d70b7bbf2530bd3fd";
  }

  static const char* value(const ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeae8b915a082df4dULL;
  static const uint64_t static_value2 = 0x70b7bbf2530bd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_task_constructor_msgs/StageDescription";
  }

  static const char* value(const ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# static description of a stage\n"
"\n"
"# unique id within task\n"
"uint32 id\n"
"\n"
"# parent id, parent_id == id means root\n"
"uint32 parent_id\n"
"\n"
"# name of this stage\n"
"string name\n"
"\n"
"# flags: interface, ...\n"
"uint32 flags\n"
"\n"
"# properties\n"
"Property[] properties\n"
"\n"
"================================================================================\n"
"MSG: moveit_task_constructor_msgs/Property\n"
"string name\n"
"string description\n"
"string type\n"
"string value\n"
;
  }

  static const char* value(const ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.parent_id);
      stream.next(m.name);
      stream.next(m.flags);
      stream.next(m.properties);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StageDescription_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_task_constructor_msgs::StageDescription_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "parent_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.parent_id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "flags: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.flags);
    s << indent << "properties[]" << std::endl;
    for (size_t i = 0; i < v.properties.size(); ++i)
    {
      s << indent << "  properties[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::moveit_task_constructor_msgs::Property_<ContainerAllocator> >::stream(s, indent + "    ", v.properties[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_TASK_CONSTRUCTOR_MSGS_MESSAGE_STAGEDESCRIPTION_H
