set(_CATKIN_CURRENT_PACKAGE "pr2_moveit_config")
set(pr2_moveit_config_VERSION "0.7.3")
set(pr2_moveit_config_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(pr2_moveit_config_PACKAGE_FORMAT "2")
set(pr2_moveit_config_BUILD_DEPENDS )
set(pr2_moveit_config_BUILD_EXPORT_DEPENDS )
set(pr2_moveit_config_BUILDTOOL_DEPENDS "catkin")
set(pr2_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(pr2_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "joint_state_publisher" "robot_state_publisher" "pr2_description" "pr2_moveit_plugins")
set(pr2_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "joint_state_publisher" "robot_state_publisher" "pr2_description" "pr2_moveit_plugins")
set(pr2_moveit_config_TEST_DEPENDS )
set(pr2_moveit_config_DOC_DEPENDS )
set(pr2_moveit_config_URL_WEBSITE "http://moveit.ros.org/")
set(pr2_moveit_config_URL_BUGTRACKER "https://github.com/ros-planning/moveit_setup_assistant/issues")
set(pr2_moveit_config_URL_REPOSITORY "https://github.com/ros-planning/moveit_setup_assistant")
set(pr2_moveit_config_DEPRECATED "")