; Auto-generated. Do not edit!


(cl:in-package moveit_task_constructor_msgs-msg)


;//! \htmlinclude ExecuteTaskSolutionFeedback.msg.html

(cl:defclass <ExecuteTaskSolutionFeedback> (roslisp-msg-protocol:ros-message)
  ((sub_id
    :reader sub_id
    :initarg :sub_id
    :type cl:integer
    :initform 0)
   (sub_no
    :reader sub_no
    :initarg :sub_no
    :type cl:integer
    :initform 0))
)

(cl:defclass ExecuteTaskSolutionFeedback (<ExecuteTaskSolutionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteTaskSolutionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteTaskSolutionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name moveit_task_constructor_msgs-msg:<ExecuteTaskSolutionFeedback> is deprecated: use moveit_task_constructor_msgs-msg:ExecuteTaskSolutionFeedback instead.")))

(cl:ensure-generic-function 'sub_id-val :lambda-list '(m))
(cl:defmethod sub_id-val ((m <ExecuteTaskSolutionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader moveit_task_constructor_msgs-msg:sub_id-val is deprecated.  Use moveit_task_constructor_msgs-msg:sub_id instead.")
  (sub_id m))

(cl:ensure-generic-function 'sub_no-val :lambda-list '(m))
(cl:defmethod sub_no-val ((m <ExecuteTaskSolutionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader moveit_task_constructor_msgs-msg:sub_no-val is deprecated.  Use moveit_task_constructor_msgs-msg:sub_no instead.")
  (sub_no m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteTaskSolutionFeedback>) ostream)
  "Serializes a message object of type '<ExecuteTaskSolutionFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'sub_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'sub_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'sub_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'sub_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'sub_no)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'sub_no)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'sub_no)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'sub_no)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteTaskSolutionFeedback>) istream)
  "Deserializes a message object of type '<ExecuteTaskSolutionFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'sub_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'sub_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'sub_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'sub_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'sub_no)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'sub_no)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'sub_no)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'sub_no)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteTaskSolutionFeedback>)))
  "Returns string type for a message object of type '<ExecuteTaskSolutionFeedback>"
  "moveit_task_constructor_msgs/ExecuteTaskSolutionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteTaskSolutionFeedback)))
  "Returns string type for a message object of type 'ExecuteTaskSolutionFeedback"
  "moveit_task_constructor_msgs/ExecuteTaskSolutionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteTaskSolutionFeedback>)))
  "Returns md5sum for a message object of type '<ExecuteTaskSolutionFeedback>"
  "5b60fd9ace7afa0cb3eb2c409d0732ed")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteTaskSolutionFeedback)))
  "Returns md5sum for a message object of type 'ExecuteTaskSolutionFeedback"
  "5b60fd9ace7afa0cb3eb2c409d0732ed")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteTaskSolutionFeedback>)))
  "Returns full string definition for message of type '<ExecuteTaskSolutionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# finished subtrajectory id / number~%uint32 sub_id~%uint32 sub_no~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteTaskSolutionFeedback)))
  "Returns full string definition for message of type 'ExecuteTaskSolutionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# finished subtrajectory id / number~%uint32 sub_id~%uint32 sub_no~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteTaskSolutionFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteTaskSolutionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteTaskSolutionFeedback
    (cl:cons ':sub_id (sub_id msg))
    (cl:cons ':sub_no (sub_no msg))
))
